// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGyDsg5DBNbrogk5wDwFqEF3hkmyE1Gco',
    appId: '1:1075358327959:web:c0d8ac99ab2aed0a80f5d2',
    messagingSenderId: '1075358327959',
    projectId: 'dietapp-52221',
    authDomain: 'dietapp-52221.firebaseapp.com',
    storageBucket: 'dietapp-52221.firebasestorage.app',
    measurementId: 'G-1BKK6D5Q51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Ajad8uRycmOvO736iPYAc3hwGL4ofWk',
    appId: '1:1075358327959:android:9f9332da99043a1280f5d2',
    messagingSenderId: '1075358327959',
    projectId: 'dietapp-52221',
    storageBucket: 'dietapp-52221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApBCmB_s_23RT9DSlSTiqsDelsMvBot-w',
    appId: '1:1075358327959:ios:0badfdea6cc07baf80f5d2',
    messagingSenderId: '1075358327959',
    projectId: 'dietapp-52221',
    storageBucket: 'dietapp-52221.firebasestorage.app',
    iosBundleId: 'com.Diet.Diet.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApBCmB_s_23RT9DSlSTiqsDelsMvBot-w',
    appId: '1:1075358327959:ios:985f11b1b145489380f5d2',
    messagingSenderId: '1075358327959',
    projectId: 'dietapp-52221',
    storageBucket: 'dietapp-52221.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGyDsg5DBNbrogk5wDwFqEF3hkmyE1Gco',
    appId: '1:1075358327959:web:694dbfea9e3f023880f5d2',
    messagingSenderId: '1075358327959',
    projectId: 'dietapp-52221',
    authDomain: 'dietapp-52221.firebaseapp.com',
    storageBucket: 'dietapp-52221.firebasestorage.app',
    measurementId: 'G-ZH5TR9V4CT',
  );

}